<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('autors', ['as'=> 'autors.index', 'uses' => 'AutorController@index']);
Route::post('autors', ['as'=> 'autors.store', 'uses' => 'AutorController@store']);
Route::get('autors/create', ['as'=> 'autors.create', 'uses' => 'AutorController@create']);
Route::put('autors/{autors}', ['as'=> 'autors.update', 'uses' => 'AutorController@update']);
Route::patch('autors/{autors}', ['as'=> 'autors.update', 'uses' => 'AutorController@update']);
Route::get('autors/{id}/delete', array('as' => 'autors.delete', 'uses' => 'AutorController@getDelete'));
Route::get('autors/{id}/confirm-delete', array('as' => 'autors.confirm-delete', 'uses' => 'AutorController@getModalDelete'));
Route::get('autors/{autors}', ['as'=> 'autors.show', 'uses' => 'AutorController@show']);
Route::get('autors/{autors}/edit', ['as'=> 'autors.edit', 'uses' => 'AutorController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('autors', ['as'=> 'autors.index', 'uses' => 'AutorController@index']);
Route::post('autors', ['as'=> 'autors.store', 'uses' => 'AutorController@store']);
Route::get('autors/create', ['as'=> 'autors.create', 'uses' => 'AutorController@create']);
Route::put('autors/{autors}', ['as'=> 'autors.update', 'uses' => 'AutorController@update']);
Route::patch('autors/{autors}', ['as'=> 'autors.update', 'uses' => 'AutorController@update']);
Route::get('autors/{id}/delete', array('as' => 'autors.delete', 'uses' => 'AutorController@getDelete'));
Route::get('autors/{id}/confirm-delete', array('as' => 'autors.confirm-delete', 'uses' => 'AutorController@getModalDelete'));
Route::get('autors/{autors}', ['as'=> 'autors.show', 'uses' => 'AutorController@show']);
Route::get('autors/{autors}/edit', ['as'=> 'autors.edit', 'uses' => 'AutorController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('autors', ['as'=> 'autors.index', 'uses' => 'AutorController@index']);
Route::post('autors', ['as'=> 'autors.store', 'uses' => 'AutorController@store']);
Route::get('autors/create', ['as'=> 'autors.create', 'uses' => 'AutorController@create']);
Route::put('autors/{autors}', ['as'=> 'autors.update', 'uses' => 'AutorController@update']);
Route::patch('autors/{autors}', ['as'=> 'autors.update', 'uses' => 'AutorController@update']);
Route::get('autors/{id}/delete', array('as' => 'autors.delete', 'uses' => 'AutorController@getDelete'));
Route::get('autors/{id}/confirm-delete', array('as' => 'autors.confirm-delete', 'uses' => 'AutorController@getModalDelete'));
Route::get('autors/{autors}', ['as'=> 'autors.show', 'uses' => 'AutorController@show']);
Route::get('autors/{autors}/edit', ['as'=> 'autors.edit', 'uses' => 'AutorController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('classificacaos', ['as'=> 'classificacaos.index', 'uses' => 'ClassificacaoController@index']);
Route::post('classificacaos', ['as'=> 'classificacaos.store', 'uses' => 'ClassificacaoController@store']);
Route::get('classificacaos/create', ['as'=> 'classificacaos.create', 'uses' => 'ClassificacaoController@create']);
Route::put('classificacaos/{classificacaos}', ['as'=> 'classificacaos.update', 'uses' => 'ClassificacaoController@update']);
Route::patch('classificacaos/{classificacaos}', ['as'=> 'classificacaos.update', 'uses' => 'ClassificacaoController@update']);
Route::get('classificacaos/{id}/delete', array('as' => 'classificacaos.delete', 'uses' => 'ClassificacaoController@getDelete'));
Route::get('classificacaos/{id}/confirm-delete', array('as' => 'classificacaos.confirm-delete', 'uses' => 'ClassificacaoController@getModalDelete'));
Route::get('classificacaos/{classificacaos}', ['as'=> 'classificacaos.show', 'uses' => 'ClassificacaoController@show']);
Route::get('classificacaos/{classificacaos}/edit', ['as'=> 'classificacaos.edit', 'uses' => 'ClassificacaoController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('classificacaos', ['as'=> 'classificacaos.index', 'uses' => 'ClassificacaoController@index']);
Route::post('classificacaos', ['as'=> 'classificacaos.store', 'uses' => 'ClassificacaoController@store']);
Route::get('classificacaos/create', ['as'=> 'classificacaos.create', 'uses' => 'ClassificacaoController@create']);
Route::put('classificacaos/{classificacaos}', ['as'=> 'classificacaos.update', 'uses' => 'ClassificacaoController@update']);
Route::patch('classificacaos/{classificacaos}', ['as'=> 'classificacaos.update', 'uses' => 'ClassificacaoController@update']);
Route::get('classificacaos/{id}/delete', array('as' => 'classificacaos.delete', 'uses' => 'ClassificacaoController@getDelete'));
Route::get('classificacaos/{id}/confirm-delete', array('as' => 'classificacaos.confirm-delete', 'uses' => 'ClassificacaoController@getModalDelete'));
Route::get('classificacaos/{classificacaos}', ['as'=> 'classificacaos.show', 'uses' => 'ClassificacaoController@show']);
Route::get('classificacaos/{classificacaos}/edit', ['as'=> 'classificacaos.edit', 'uses' => 'ClassificacaoController@edit']);

});
